ALTER USER SA SET LOCAL TRUE
CREATE SEQUENCE PUBLIC.MY_SEQ_GEN AS INTEGER START WITH 1 INCREMENT BY 12
CREATE MEMORY TABLE PUBLIC.GREENFIELD(ID INTEGER PRIMARY KEY,BEGIN_TS TIMESTAMP,DATABUNDLE VARCHAR(4000))
